server:
  port: 7777
spring:
  mail:
    username: 976869901@qq.com
    password: sacqlktfajsebcbe
    host: smtp.qq.com
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
